### ISSUE TITLE
Run celery and redis automatically on runserver

### ISSUE THREAD

**Issue by prihoda** [prihoda/golem#10]
If possible, add a hook to run required services automatically on manage.py runserver:

- celery
- celerybeat
- redis
- ngrok tunnel (if configured)

It will only be used when running the bot locally (otherwise the wsgi script & separate services will be used). Path to binaries will to be configured in settings.py.

https://github.com/rfk/django-supervisor

**Comment by mzilinec** [comment]
Will be done by Golm init script, see 146c55a9abf0b42c8be3e8bfaf28ac278921b5ee .
Depends on #33 .
