### ISSUE TITLE
Golem as an executable

### ISSUE THREAD

**Issue by prihoda** [prihoda/golem#17]
I've got an idea for an interesting usability improvement, in the far far future 😉 

Golem could be packaged as a standalone executable. It will be best illustrated on example usage:

```sh
pip install golm
# installing GOLM...

golm init mybot
# creating folder mybot...

ls mybot
# settings.py
# wsgi.py
# chatbots/
#   default.py
#   transport.js
# tests/
# entities/

golm mybot run
# running on port 8080...
```

User visits `localhost:8080` and BAM, he can chat with his bot!

The advantages:
- Three commands to run your first Hello World bot
- Minimalistic folder structure, users know what belongs to them
- Users don't have to learn django
- Maybe users don't even have to learn python! I'm sure we could somehow prepare a lightweight support for node.js (which is what all the cool kids are using)
- Easier for us to manage and configure whole golem django project instead of just django apps
- Web GUI is "owned" by golem - the chat GUI could be on the root page!
- Flows could be saved in the database -> editing flows in GUI 🔥🔥🔥 

The disadvantages:
- We would have to figure out how to do it 😄 
- Users would not be able to create their own django apps (models, views...) anymore
- Not sure we can package and run all our dependencies so easily (in both local and production environment!)

**Comment by mzilinec** [comment]
See 146c55a9abf0b42c8be3e8bfaf28ac278921b5ee.

**Comment by mzilinec** [comment]
What it does right now:
- install golem + dependencies
- clone a skeleton project
- start celery + django + redis
