### ISSUE TITLE
Enable default state in each flow

### ISSUE THREAD

**Issue by prihoda** [prihoda/golem#21]
A default state could be optionally defined in each flow to override the default.root state. It would be accessed when no suitable state is found for a user's message while in given flow. This would enable skills to have their own fallback action.

**Comment by mzilinec** [comment]
In the new flow system, I think it would be best to have an attribute called unsupported.
The bot would just move there when the message is not supported.
Furthermore, there is a method to prevent this from happening - either by marking the state as `blocking`, or by using `supported entities`.
For example:
```yaml
default:
  unsupported: default.unsupported  # what's better? state or function?
  foo:
    action: abcd
  bar:
    unsupported: unsupported_action
    action: qwe
